api/urls.py
from django.urls import path
from api.views import PostAPIView

urlpatterns = [
    path('post/<int:pk>/', PostAPIView.as_view()),
]

network/urls.py
from django.urls import path

from . import views

app_name = "network"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:user_id>", views.profile, name="profile"),
    path("following", views.following, name="following"),

    # API Routes
    # path("posts/<int:post_id>", views.posts, name="posts"),
    # path('posts/', views.post_list),
    # path('post/<int:pk>/', views.post_detail),
]

social/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
    path('api/', include('api.urls')),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    """ User model """


class Post(models.Model):
    """ Post model """

    poster = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="poster")
    post = models.TextField()
    post_time = models.DateTimeField(default=timezone.now)
    likers = models.ManyToManyField(User, related_name="post_likers")

    def serialize(self):
        """ Converts the post content to json format """
        return {
            "id": self.id,
            "poster": self.poster.username,
            "likers": [liker.id for liker in self.likers.all()],
            "post": self.post,
            "timestamp": self.post_time.strftime("%b %-d %Y, %-I:%M %p"),
        }

    def likes(self):
        """ Total likes counter """
        return self.likers.all().count()


class Follow(models.Model):
    """ Following model """

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="follow_user")
    following = models.ManyToManyField(User, related_name="follow_following")
    followers = models.ManyToManyField(User, related_name="follow_followers")

network/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt


from network.models import User, Post, Follow


class PostForm(forms.Form):
    """ Post Form """

    post = forms.CharField(label="post",
                           widget=forms.Textarea(
                               attrs={'placeholder': ' Write a new post',
                                      'rows': 1,
                                      'cols': 45,
                                      'style': 'margin-bottom:0'}))


def index(request):
    """ Index route handler """

    # Make a list of all posts
    post_list = Post.objects.all().order_by('-post_time')

    # Create a paginator instance for 10 posts per page
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Make the html context
    context = {
        "post_form": PostForm(prefix='post'),
        'page_obj': page_obj,
    }

    # if the user atttemps to write a new post
    if request.method == "POST":

        # find the current user
        user = User.objects.get(pk=int(request.user.id))

        # attemp to post the request
        post(request, user, context)

    # finally load the index page
    return render(request, "network/index.html", context)


def login_view(request):
    """ Login view handler """
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


@login_required
def logout_view(request):
    """ Logout view handler """
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    """register route handler"""

    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:
        return render(request, "network/register.html")


def profile(request, user_id):
    """user profile handler"""

    # find the profile user
    profile_user = User.objects.get(pk=int(user_id))

    # Make a list of all of the profile user posts
    post_list = Post.objects.filter(poster=profile_user).order_by('-post_time')

    # Create a paginator instance for 10 posts per page
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Get the profile follow data
    # if it does not exists make a new one and get that
    try:
        profile_follow_obj = Follow.objects.get(user=profile_user)
    except ObjectDoesNotExist:
        profile_follow_obj = Follow.objects.create(user=profile_user)
        profile_follow_obj = Follow.objects.get(user=profile_user)

    # find and count all following and followrs of the profile user

    profile_following = profile_follow_obj.following.all()
    profile_following_count = profile_following.count()

    profile_followers = profile_follow_obj.followers.all()
    profile_followers_count = profile_followers.count()

    # create a new html context
    context = {
        'profile_user': profile_user,
        'page_obj': page_obj,
        "following_count": profile_following_count,
        "followers_count": profile_followers_count,
    }

    # if a user is logged in and is viewing the profile:
    if request.user.id:

        # find the current user
        current_user = User.objects.get(pk=int(request.user.id))

        # uodate html context for the follow button color
        context['follow_color'] = ("primary"
                                   if current_user in profile_followers
                                   else "outline-primary")
        # add current user to the context
        context['current_user'] = current_user

        # Get the current user follow data
        # if it does not exists make a new one and get that
        try:
            current_follow_obj = Follow.objects.get(user=current_user)
        except ObjectDoesNotExist:
            current_follow_obj = Follow.objects.create(user=current_user)
            current_follow_obj = Follow.objects.get(user=current_user)

    # if current user attemps to follow/unfollow the profile user:
    if 'follow' in request.POST:

        # Attemp to update the follow state of profile and current user
        follow(request,
               current_user, profile_user,
               profile_followers,
               profile_follow_obj, current_follow_obj,
               profile_followers_count, context)
    
    # finally load the profile page
    return render(request, "network/profile.html", context)


@login_required
def post(request, current_user, context):
    """ post handler """

    # a\Attemp to save the post
    if 'post' in request.POST:

        form = PostForm(request.POST, prefix='post')

        if form.is_valid():

            # save the post
            last_post = form.cleaned_data["post"]
            post_obj = Post()
            post_obj.post = last_post
            post_obj.poster = current_user
            post_obj.save()

        else:
            context["post_form"] = form


@login_required
def follow(request,
           current_user, profile_user,
           profile_followers,
           profile_follow_obj, current_follow_obj,
           profile_followers_count, context):
    """add/remove follow list handler"""

    if 'follow' in request.POST:

        # update the following and followers data for the current user and profile user
        if current_user in profile_followers:
            profile_follow_obj.followers.remove(current_user)
            current_follow_obj.following.remove(profile_user)
            color = "outline-primary"
            profile_followers_count -= 1
        else:
            profile_follow_obj.followers.add(current_user)
            current_follow_obj.following.add(profile_user)
            profile_followers_count += 1
            color = "primary"

        profile_follow_obj.save()
        current_follow_obj.save()
        context["follow_color"] = color
        context["followers_count"] = profile_followers_count


@login_required
def following(request):
    """ following page handler """

    # get the current user
    current_user = User.objects.get(pk=int(request.user.id))

    # Get the current user follow data
    # if it does not exists make a new one and get that
    try:
        current_follow_obj = Follow.objects.get(user=current_user)
    except ObjectDoesNotExist:
        current_follow_obj = Follow.objects.create(user=current_user)
        current_follow_obj = Follow.objects.get(user=current_user)
    
    # find all users that the current user follows
    following_obj = current_follow_obj.following.all()

    # Make a list of all posts from the users the current user follows
    post_list = Post.objects.filter(
        poster__in=following_obj).order_by('-post_time')

    # Create a paginator instance for 10 posts per page
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Make the html context
    context = {
        "post_form": PostForm(prefix='post'),
        'page_obj': page_obj,
    }

    # if the user atttemps to write a new post
    if request.method == "POST":

        # attemp to post the request
        post(request, current_user, context)

    # finally load the index page
    return render(request, "network/index.html", context)


@csrf_exempt
@login_required
def posts(request, post_id):
    """ posts API route """

    # Query for requested Post
    try:
        post_obj = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        return JsonResponse({"error": "Post not found."}, status=404)

    # Return email contents
    if request.method == "GET":
        return JsonResponse(post_obj.serialize())

    # Update whether post is liked or should be edited
    elif request.method == "PUT":

        # Get the json data
        data = json.loads(request.body)

        # Attemp to edit a post content
        if data.get("edit") is not None:
            post_obj.post = data["edit"]


network/templates/network/index.html
{% extends "network/layout.html" %}

{% block body %}
<div class='mx-auto'>
    {% load static %}
    {% if user.is_authenticated %}
    <form action="{% url 'network:index' %}" method="post" class="mx-auto" style="width:40%;">
        {% csrf_token %}
        <div class="form-group mb-0"> {{post_form.post }} </div>
        <input name = "post" class="btn btn-primary" type="submit" value="Post">
    </form>
    <p></p>
    {% endif %}

    <P class="border rounded-top bg-info text-white mx-auto my-0 p-1" style="width:40%">Posts</p>

    <div class="border rounded-bottom mx-auto my-0" style="width:40% ;">

        <ul class="pagination mx-auto my-0" style="width:90% ;">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>   
                <li class="page-item"></li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>           
            {% endif %}
            {% if page_obj.has_next %}                
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
            {% endif %}
            <li class="page-item my-auto p-1 text-primary ml-auto">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </li>
        </ul>
    
        {% for post in page_obj %}
            <p class="text-info d-flex rounded mx-auto my-0 p-1" style="width:90% ;">
                <a id="poster{{post.id}}" href="{% url 'network:profile' post.poster.id %}"> {{post.poster}}</a>         
                <small class="text-secondary text-right p-1">
                    posted {{post.post_time}} 
                </small>
            </p>
            <p id="post{{post.id}}" class="d-flex border rounded mx-auto bg-light text-sm-left-justify p-1 my-0" style="width:90%;">{{post.post}} </p>
            
            <div class="row mx-auto my-0 p-1" style="width:90%;">
                
                {% if user.id in post.serialize.likers %}
                    <img id="like{{post.id}}" onclick="like('{{post.id}},{{user.id}}')" class="ml-1 mb-2 mt-1" src="{% static 'network/like1.png' %}" alt="No image available" width="20" height="20">
                {% else %}
                    <img id="like{{post.id}}" onclick="like('{{post.id}},{{user.id}}')" class="ml-1 mb-2 mt-1" src="{% static 'network/like.png' %}" alt="No image available" width="20" height="20">
                {% endif %}
                
                <p id="likes{{post.id}}" class="mb-1 ml-1 text-success">{{post.likes}}</p>
                
                {% if user.id == post.poster.id %} 
                    <button id="edit{{post.id}}" onclick="edit('{{post.id}}')" class="btn btn-outline-primary ml-auto">Edit</button>
                {% endif %}
            </div>
            
        {% endfor %}
    </div>

</div>    
{% endblock %}

{% block script %}
    <script src="{% static 'network/util.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Network</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="#"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body">
            <div class="container">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

<div class='w-25 mx-auto'>

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>

</div>
{% endblock %}

network/templates/network/profile.html
{% extends "network/layout.html" %}

{% block body %}

{% load static %}

<div class='mx-auto'>
    
    <h2 class='mx-auto' style='width:40%;'>{{profile_user.username}}</h2>

    <p class='mx-auto text-info' style='width:40%;'>Followers: {{followers_count}} Following: {{following_count}} </p>

    {% if user.is_authenticated and user.id != profile_user.id %}
    <form action="{% url 'network:profile' profile_user.id %}" method="post" class='mx-auto text-info' style='width:40%;'>
        {% csrf_token %}
        <input name = "follow" class="btn btn-{{follow_color}} rounded-pill" style="font-size:80%;" type="submit" value="Follow">
    </form>
    <p></p>
    {% endif%}

    
    <P class="border rounded-top bg-info text-white mx-auto my-0 p-1" style="width:40%">Posts</p>

    <div class="border rounded-bottom mx-auto my-0" style="width:40% ;">

        <ul class="pagination mx-auto my-0" style="width:90% ;">
            {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>   
                <li class="page-item"></li><a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a></li>           
            {% endif %}
            {% if page_obj.has_next %}                
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
            {% endif %}
            <li class="page-item my-auto p-1 text-primary ml-auto">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </li>
        </ul>
    
        {% for post in page_obj %}
            <p class="text-info d-flex rounded mx-auto my-0 p-1" style="width:90% ;">
                <a href="{% url 'network:profile' post.poster.id %}"> {{post.poster}}</a>         
                <small class="text-secondary text-right p-1">
                    posted {{post.post_time}} 
                </small>
            </p>
            <p id="post{{post.id}}" class="d-flex border rounded mx-auto bg-light text-sm-left-justify p-1 my-0" style="width:90%;">{{post.post}} </p>

            <div class="row mx-auto my-0 p-1" style="width:90%;">
                
                {% if user.id in post.serialize.likers %}
                    <img id="like{{post.id}}" onclick="like('{{post.id}},{{user.id}}')" class="ml-1 mb-2 mt-1" src="{% static 'network/like1.png' %}" alt="No image available" width="20" height="20">
                {% else %}
                    <img id="like{{post.id}}" onclick="like('{{post.id}},{{user.id}}')" class="ml-1 mb-2 mt-1" src="{% static 'network/like.png' %}" alt="No image available" width="20" height="20">
                {% endif %}
                
                <p id="likes{{post.id}}" class="ml-1">{{post.likes}}</p>
                
                {% if user.id == post.poster.id %} 
                    <button id="edit{{post.id}}" onclick="edit('{{post.id}}')" class="btn btn-outline-primary ml-auto">Edit</button>
                {% endif %}
            </div>
        {% endfor %}
    </div>

</div>    
{% endblock %}

{% block script %}
    <script src="{% static 'network/util.js' %}"></script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

<div class='w-25 mx-auto'>

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>

</div>
{% endblock %}